# Generated by Django 2.2.5 on 2019-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frist',
            name='zeitraum',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
