# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frist', '0002_auto_20190918_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fristzuordenbarkeit',
            name='frist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuordenbarkeiten', to='frist.Frist'),
        ),
        migrations.AlterField(
            model_name='fristzuordenbarkeit',
            name='rolle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fristzuordenbarkeiten', to='rolle.Rolle'),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='frist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungen', to='frist.Frist'),
        ),
    ]
