# Generated by Django 2.2.5 on 2019-09-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berechtigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Freigabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untergruppen', models.BooleanField()),
                ('berechtigung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolle.Berechtigung')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolle.Rolle')),
            ],
        ),
    ]
