# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freigabe',
            name='berechtigung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freigaben', to='rolle.Berechtigung'),
        ),
        migrations.AlterField(
            model_name='freigabe',
            name='rolle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freigaben', to='rolle.Rolle'),
        ),
    ]
