# Generated by Django 2.2.5 on 2019-09-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitaet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('thema', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorab', models.CharField(choices=[('x', 'Anwesend'), ('-', 'Abwesend'), ('?', 'Unklar')], default='?', max_length=1)),
                ('ist', models.CharField(choices=[('x', 'Anwesend'), ('-', 'Abwesend'), ('?', 'Unklar')], default='?', max_length=1)),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienst.Dienst')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitaet.Person')),
            ],
        ),
    ]
