# Generated by Django 2.2.5 on 2019-09-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruppe', '0002_auto_20190918_2124'),
        ('dienst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienst',
            name='gruppe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gruppe.Gruppe'),
            preserve_default=False,
        ),
    ]
