# Generated by Django 2.2.5 on 2019-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dienst', '0002_dienst_gruppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dienst',
            name='datum',
        ),
        migrations.AddField(
            model_name='dienst',
            name='ende',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dienst',
            name='start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
