# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dienst', '0004_auto_20190920_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienst',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dienste', to='gruppe.Gruppe'),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='dienst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='dienst.Dienst'),
        ),
    ]
