# Generated by Django 2.2.5 on 2019-09-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rolle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitaet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('entitaet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entitaet.Entitaet')),
                ('bezeichnung', models.CharField(max_length=70)),
            ],
            bases=('entitaet.entitaet',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entitaet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entitaet.Entitaet')),
                ('mail', models.EmailField(max_length=254)),
                ('authCode', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('entitaet.entitaet',),
        ),
        migrations.CreateModel(
            name='Rollenzugehoerigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateField()),
                ('bis', models.DateField()),
                ('entitaet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitaet.Entitaet')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolle.Rolle')),
            ],
        ),
    ]
