# Generated by Django 2.2.5 on 2019-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitaet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='authCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rollenzugehoerigkeit',
            name='bis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
