# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entitaet', '0003_auto_20190918_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitaet',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitaeten', to='gruppe.Gruppe'),
        ),
        migrations.AlterField(
            model_name='rollenzugehoerigkeit',
            name='entitaet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollenzugehoerigkeiten', to='entitaet.Entitaet'),
        ),
        migrations.AlterField(
            model_name='rollenzugehoerigkeit',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollenzugehoerigkeiten', to='gruppe.Gruppe'),
        ),
        migrations.AlterField(
            model_name='rollenzugehoerigkeit',
            name='rolle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollenzugehoerigkeiten', to='rolle.Rolle'),
        ),
    ]
