# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruppe', '0002_auto_20190918_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppe',
            name='uebergeordnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='untergeordnet', to='gruppe.Gruppe'),
        ),
    ]
