# Generated by Django 2.2.5 on 2019-09-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitaet', '0003_auto_20190918_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lehrgang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('kuerzel', models.CharField(max_length=10)),
                ('austragung', models.CharField(choices=[('b', 'Bundesschule'), ('r', 'Regionalbereich')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Priorisiert gewünscht'), ('o', 'Gewünscht wenn möglich'), ('i', 'Nur Last-Minute'), ('b', 'Besucht')], default='i', max_length=1)),
                ('lehrgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrgaenge.Lehrgang')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lehrgang_teilnahmen', to='entitaet.Person')),
            ],
        ),
    ]
