# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lehrgaenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnahme',
            name='lehrgang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='lehrgaenge.Lehrgang'),
        ),
    ]
